// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Store struct {
	ID                 int64            `json:"id"`
	ProductName        string           `json:"product_name"`
	ProductDescription pgtype.Text      `json:"product_description"`
	AvailableQuantity  pgtype.Numeric   `json:"available_quantity"`
	ReservedQuantity   pgtype.Numeric   `json:"reserved_quantity"`
	Price              pgtype.Numeric   `json:"price"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}
