// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	OrderID     int32            `json:"order_id"`
	UserID      int32            `json:"user_id"`
	OrderDate   pgtype.Timestamp `json:"order_date"`
	StatusStaus string           `json:"status_staus"`
	TotalAmount pgtype.Numeric   `json:"total_amount"`
	PaymentID   pgtype.Text      `json:"payment_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type OrderItem struct {
	OrderItemID int32          `json:"order_item_id"`
	OrderID     int32          `json:"order_id"`
	ProductID   int32          `json:"product_id"`
	ProductName string         `json:"product_name"`
	Price       pgtype.Numeric `json:"price"`
	Quantity    int32          `json:"quantity"`
	Subtotal    pgtype.Numeric `json:"subtotal"`
}
